version: '3.9'

services:
  postgres:
    image: ankane/pgvector
    container_name: chatbot_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: chatbot_db
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: