# Generated by Django 5.1.7 on 2025-03-20 09:55

import django.db.models.deletion
from django.db import migrations, models


def create_default_conversation(apps, schema_editor):
    Conversation = apps.get_model('chatbot', 'Conversation')
    ChatMessage = apps.get_model('chatbot', 'ChatMessage')

    default_conv = Conversation.objects.create(user_identifier='default')

    ChatMessage.objects.filter(conversation__isnull=True).update(conversation=default_conv)

class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=models.CASCADE, related_name='messages', to='chatbot.conversation'),
        ),
        migrations.RunPython(create_default_conversation),
        migrations.AlterField(
            model_name='chatmessage',
            name='conversation',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='messages', to='chatbot.conversation'),
        ),
    ]