# Generated by Django 5.1.7 on 2025-03-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(max_length=100, verbose_name='Nazwa strony')),
                ('owner_email', models.EmailField(max_length=254, verbose_name='Email właściciela')),
                ('gpt_prompt', models.TextField(default='Jesteś chatbotem obsługującym klientów sklepu internetowego.', verbose_name='Prompt GPT')),
            ],
        ),
    ]
