# Generated by Django 5.1.7 on 2025-03-26 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_tenant_delete_websitesettings_conversation_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='chatbot.tenant'),
        ),
    ]
