# Generated by Django 5.1.7 on 2025-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_conversation_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_position',
            field=models.CharField(choices=[('bottom-right', 'Dół strony (prawy)'), ('bottom-left', 'Dół strony (lewy)'), ('side-right', 'Boczny (prawy)'), ('side-left', 'Boczny (lewy)'), ('hamburger', 'Przycisk hamburger')], default='bottom-right', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_title',
            field=models.CharField(default='Chatbot', max_length=50),
        ),
    ]
