# Generated by Django 5.1.7 on 2025-04-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_document'),
        ('chatbot', '0012_auto_20250402_1755'),
    ]

    operations = [
    ]
