# Generated by Django 5.1.7 on 2025-04-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-last_message_at']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='source',
            field=models.CharField(choices=[('faq', 'FAQ'), ('document', 'Document'), ('gpt', 'OpenAI'), ('fallback', 'Fallback'), ('manual', 'Manual')], default='gpt', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='token_count',
            field=models.PositiveIntegerField(default=0, help_text='Liczba tokenów tej wiadomości (jeśli dotyczy)'),
        ),
        migrations.AddField(
            model_name='chatusagelog',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='chatusagelog',
            name='model_used',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50),
        ),
        migrations.AddField(
            model_name='chatusagelog',
            name='source',
            field=models.CharField(choices=[('faq', 'FAQ'), ('document', 'Document'), ('gpt', 'OpenAI'), ('fallback', 'Fallback'), ('manual', 'Manual')], default='gpt', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='source',
            field=models.CharField(default='widget', max_length=30),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=24),
        ),
    ]
