# Generated by Django 5.1.7 on 2025-04-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_promptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
