# Generated by Django 5.1.7 on 2026-08-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_analytics_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='blad_powiadomienia',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='powiadomiono_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
