# Generated by Django 5.2.17 on 2026-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_slad_powiadomienia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlog',
            name='source',
            field=models.CharField(choices=[('faq', 'FAQ'), ('document', 'RAG'), ('gpt', 'Brak wiedzy firmy'), ('rozmowa', 'Rozmowa bez wiedzy firmy')], max_length=50),
        ),
    ]
