# Generated by Django 5.1.7 on 2025-06-10 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscription_client'),
        ('chat', '0005_chatfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='ID Sesji')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP użytkownika')),
                ('user_agent', models.TextField(blank=True, verbose_name='Przeglądarka użytkownika')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna sesja')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='accounts.client', verbose_name='Konfiguracja Chatbota')),
            ],
            options={
                'verbose_name': 'Sesja Chat',
                'verbose_name_plural': 'Sesje Chatów',
                'indexes': [models.Index(fields=['session_id'], name='chat_chat_session_19463b_idx'), models.Index(fields=['client', 'started_at'], name='chat_chat_client__e2dfb3_idx')],
            },
        ),
    ]
