# Generated by Django 5.1.7 on 2025-06-18 13:22

import uuid
from django.db import migrations, models


def populate_session_ids(apps, schema_editor):
    Conversation = apps.get_model("chat", "Conversation")
    for conversation in Conversation.objects.filter(session_id__isnull=True):
        conversation.session_id = uuid.uuid4()
        conversation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat'),  # lub aktualna ostatnia
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_session_ids),
    ]

