# Generated by Django 5.2.17 on 2026-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_zrodlo_rozmowy'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptlog',
            name='tokeny_wejscia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promptlog',
            name='tokeny_wyjscia',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
