# Generated by Django 5.2.17 on 2026-09-30 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0043_usuwanie_retencja"),
        ("chat", "0007_promptlog_tokeny_wejscia_promptlog_tokeny_wyjscia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatusagelog",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_requests",
                to="chat.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="promptlog",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.conversation",
            ),
        ),
        migrations.CreateModel(
            name="UsunietaRozmowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("skrot_sesji", models.CharField(max_length=64)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.tenant"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "skrot_sesji"), name="usunieta_sesja_firmy"
                    )
                ],
            },
        ),
    ]
