# Generated by Django 5.1.7 on 2025-04-18 14:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitationtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitationtoken',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.RenameField(
            model_name='invitationtoken',
            old_name='max_uses',
            new_name='max_users',
        ),
        migrations.RenameField(
            model_name='invitationtoken',
            old_name='uses',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='invitationtoken',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='gpt_prompt',
        ),
        migrations.AddField(
            model_name='invitationtoken',
            name='duration',
            field=models.CharField(choices=[('1h', '1 Hour'), ('12h', '12 Hours'), ('1d', '1 Day'), ('7d', '7 Days')], default='1d', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='invitationtoken',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='regulamin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='token_limit',
            field=models.PositiveIntegerField(default=100000, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='widget_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='widget_position',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='widget_title',
            field=models.CharField(default='Chatbot', max_length=100),
        ),
    ]
