# Generated by Django 5.1.7 on 2025-06-10 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_gpt_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('message_limit', models.PositiveIntegerField(default=1000, help_text='Miesięczny limit wiadomości dla wszystkich chatbotów firmy', verbose_name='Limit wiadomości/miesiąc')),
                ('current_message_count', models.PositiveIntegerField(default=0, verbose_name='Liczba użytych wiadomości')),
                ('billing_cycle_start', models.DateField(auto_now_add=True, verbose_name='Start cyklu rozliczeniowego')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Subskrypcja',
                'verbose_name_plural': 'Subskrypcje',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Np. 'Chatbot Sklepu Głównego'", max_length=100, verbose_name='Nazwa konfiguracji')),
                ('website_url', models.URLField(help_text='Gdzie zostanie osadzony chatbot', verbose_name='Adres URL strony')),
                ('api_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Klucz API')),
                ('chatbot_config', models.JSONField(default=dict, help_text='Ustawienia chatbota w formacie JSON', verbose_name='Konfiguracja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Twórca konfiguracji')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='accounts.tenant', verbose_name='Firma kliencka')),
            ],
            options={
                'verbose_name': 'Konfiguracja Chatbota',
                'verbose_name_plural': 'Konfiguracje Chatbotów',
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
