# Generated by Django 5.1.7 on 2025-06-18 13:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_subscription_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterField(
            model_name='tenant',
            name='api_key',
            field=models.UUIDField(default=accounts.models.generate_api_key, editable=False, unique=True),
        ),
    ]
