# Generated by Django 5.1.7 on 2025-06-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_subscription_options_alter_tenant_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='widget_position',
            field=models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default='right', max_length=25),
        ),
    ]
