# Generated by Django 5.1.7 on 2026-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_tenant_widget_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='branding_mode',
            field=models.CharField(choices=[('smart', 'Smart (domyślna marka)'), ('white_label', 'White-label (marka klienta)')], default='smart', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_avatar',
            field=models.FileField(blank=True, null=True, upload_to='widget_branding/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_footer_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_logo',
            field=models.FileField(blank=True, null=True, upload_to='widget_branding/'),
        ),
    ]
