# Generated by Django 5.1.7 on 2026-08-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_tenant_branding_mode_tenant_widget_avatar_and_more'),
        ('chat', '0002_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
