# Generated by Django 5.1.7 on 2026-08-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='data_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='Po ilu dniach automatycznie usuwać rozmowy i logi. 0 = nie usuwaj.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='privacy_policy_url',
            field=models.URLField(blank=True, default='', help_text='Link do polityki prywatności pokazywany w widgecie.'),
        ),
    ]
