# Generated by Django 5.1.7 on 2026-08-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_tenant_data_retention_days_tenant_privacy_policy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_suggested_questions',
            field=models.TextField(blank=True, default='', help_text='Propozycje pytań startowych, po jednym w wierszu (pokazujemy do 4).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_welcome_message',
            field=models.TextField(blank=True, default='', help_text='Pierwsza wiadomość bota. Puste = okno otwiera się bez powitania.'),
        ),
    ]
