# Generated by Django 5.1.7 on 2026-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_tenant_widget_suggested_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_languages',
            field=models.CharField(default='pl', help_text='Kody języków po przecinku, np. pl,en. Pierwszy jest domyślny — użyjemy go, gdy pytanie przyjdzie w języku spoza listy.', max_length=64),
        ),
    ]
