# Generated by Django 5.1.7 on 2026-08-09 17:37

from django.db import migrations, models

OBSLUGIWANE = {"pl", "en", "uk", "de", "ru", "cs"}


def przenies_domyslny_jezyk(apps, schema_editor):
    """
    Dotąd domyślnym językiem był pierwszy element widget_languages. Bez tego
    przeniesienia klient z listą "en,pl" dostałby nagle polski jako zapasowy,
    bo nowe pole ma default="pl".
    """
    Tenant = apps.get_model("accounts", "Tenant")
    for tenant in Tenant.objects.all().iterator():
        kody = [
            kod.strip().lower()
            for kod in (tenant.widget_languages or "").replace(";", ",").split(",")
            if kod.strip() in OBSLUGIWANE
        ]
        if kody and kody[0] != tenant.widget_default_language:
            tenant.widget_default_language = kody[0]
            tenant.save(update_fields=["widget_default_language"])


def cofnij(apps, schema_editor):
    """Pole znika razem z migracją — nie ma czego odtwarzać."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_tenant_widget_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_default_language',
            field=models.CharField(choices=[('pl', 'polski'), ('en', 'angielski'), ('uk', 'ukraiński'), ('de', 'niemiecki'), ('ru', 'rosyjski'), ('cs', 'czeski')], default='pl', help_text="W trybie 'jeden język' — język odpowiedzi. W trybie 'auto' — język zapasowy, gdy pytanie przyjdzie w języku spoza listy.", max_length=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_language_mode',
            field=models.CharField(choices=[('fixed', 'Zawsze jeden język'), ('auto', 'Dopasuj do języka pytania')], default='auto', help_text='Czy bot trzyma się jednego języka, czy dopasowuje go do pytania.', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='widget_languages',
            field=models.CharField(default='pl', help_text="Kody języków po przecinku, np. pl,en. Używane tylko w trybie 'auto'.", max_length=64),
        ),
        migrations.RunPython(przenies_domyslny_jezyk, cofnij),
    ]
