# Generated by Django 5.1.7 on 2026-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tenant_widget_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_proactive_delay_seconds',
            field=models.PositiveIntegerField(default=30, help_text='Po ilu sekundach na stronie pokazać zaczepkę.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_proactive_enabled',
            field=models.BooleanField(default=False, help_text='Czy pokazywać zaczepkę odwiedzającemu, który nie zaczął rozmowy.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='widget_proactive_texts',
            field=models.JSONField(blank=True, default=dict, help_text='Teksty zaczepki per język, np. {"pl": "Pomóc w czymś?"}.'),
        ),
    ]
