# Generated by Django 5.1.7 on 2026-08-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_tenant_widget_proactive_delay_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='widget_hide_branding',
            field=models.BooleanField(default=False, help_text='Ukryć stopkę "Powered by Sm-art" (plan Grow i wyżej).'),
        ),
    ]
