# Generated by Django 5.1.7 on 2026-08-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_tenant_widget_hide_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alert_threshold_sent',
            field=models.PositiveIntegerField(default=0, verbose_name='Ostatnio wysłany próg alertu (%)'),
        ),
    ]
