# Generated by Django 5.1.7 on 2026-08-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_subscription_alert_threshold_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WidgetDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Nazwa hosta bez schematu i bez www, np. sklep.pl', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_domains', to='accounts.tenant')),
            ],
            options={
                'ordering': ['host'],
                'unique_together': {('tenant', 'host')},
            },
        ),
    ]
