# Generated by Django 5.1.7 on 2026-08-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_widgetdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='powiadom_o_rozmowie',
            field=models.BooleanField(default=False, verbose_name='Powiadamiaj o każdej rozpoczętej rozmowie'),
        ),
    ]
