# Generated by Django 5.1.7 on 2026-08-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_powiadomienie_o_rozmowie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='raport_tygodniowy',
            field=models.BooleanField(default=True, verbose_name='Cotygodniowy raport luk w wiedzy'),
        ),
    ]
