# Generated by Django 5.1.7 on 2026-08-26 15:54

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rejestr_bez_wlasnej_domeny'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.MenedzerUzytkownikow()),
            ],
        ),
    ]
