# Generated by Django 5.1.7 on 2026-08-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alert_konca_dla',
            field=models.DateField(blank=True, null=True, verbose_name='Data końca, której dotyczy wysłany próg'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='alert_konca_prog',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Ostatnio wysłany próg końca (dni)'),
        ),
    ]
