# Generated by Django 5.2.17 on 2026-09-02 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_subscription_alert_konca_dla_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WpisDziennika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uzytkownika', models.CharField(blank=True, default='', max_length=150)),
                ('czas', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metoda', models.CharField(max_length=10)),
                ('sciezka', models.CharField(max_length=255)),
                ('status', models.PositiveSmallIntegerField()),
                ('adres_ip', models.CharField(blank=True, default='', max_length=45)),
                ('tenant', models.ForeignKey(blank=True, help_text='Puste przy zdarzeniach sprzed rozpoznania firmy, np. nieudane logowanie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dziennik', to='accounts.tenant')),
                ('uzytkownik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wpisy_dziennika', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wpis dziennika',
                'verbose_name_plural': 'Dziennik audytowy',
                'ordering': ['-czas'],
                'indexes': [models.Index(fields=['tenant', '-czas'], name='accounts_wp_tenant__f0e889_idx')],
            },
        ),
    ]
