# Generated by Django 5.2.17 on 2026-09-02 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_wpisdziennika'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugiSkladnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sekret', models.CharField(max_length=64)),
                ('potwierdzony_od', models.DateTimeField(blank=True, null=True)),
                ('ostatni_krok', models.BigIntegerField(blank=True, null=True)),
                ('utworzony', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drugi_skladnik', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drugi składnik',
                'verbose_name_plural': 'Drugie składniki',
            },
        ),
        migrations.CreateModel(
            name='KodZapasowy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skrot', models.CharField(db_index=True, max_length=64)),
                ('uzyty', models.DateTimeField(blank=True, null=True)),
                ('utworzony', models.DateTimeField(auto_now_add=True)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kody_zapasowe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kod zapasowy',
                'verbose_name_plural': 'Kody zapasowe',
            },
        ),
    ]
