# Generated by Django 5.2.17 on 2026-09-02 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_drugiskladnik_kodzapasowy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaneRozliczeniowe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(help_text='Pełna nazwa firmy albo imię i nazwisko, jeśli działalność nierejestrowana.', max_length=200, verbose_name='Nazwa na fakturze')),
                ('nip', models.CharField(blank=True, default='', max_length=15, verbose_name='NIP')),
                ('ulica', models.CharField(max_length=200, verbose_name='Ulica i numer')),
                ('kod_pocztowy', models.CharField(max_length=12)),
                ('miasto', models.CharField(max_length=100)),
                ('kraj', models.CharField(default='PL', max_length=2, verbose_name='Kod kraju')),
                ('utworzone', models.DateTimeField(auto_now_add=True)),
                ('zmienione', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dane_rozliczeniowe', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Dane rozliczeniowe',
                'verbose_name_plural': 'Dane rozliczeniowe',
            },
        ),
    ]
