# Generated by Django 5.2.17 on 2026-09-02 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_danerozliczeniowe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZliczenieOdmow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('powod', models.CharField(choices=[('brak_klucza', 'Żądanie bez klucza API'), ('zly_klucz', 'Nieznany klucz API'), ('brak_subskrypcji', 'Firma bez subskrypcji'), ('brak_aktywnej', 'Żadna subskrypcja nie jest aktywna'), ('subskrypcja_wygasla', 'Subskrypcja poza datami ważności'), ('limit_wiadomosci', 'Wyczerpany limit wiadomości')], max_length=32)),
                ('dzien', models.DateField()),
                ('liczba', models.PositiveIntegerField(default=0)),
                ('pierwsza', models.DateTimeField()),
                ('ostatnia', models.DateTimeField()),
                ('zgloszone', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='odmowy_widgetu', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Zliczenie odmów widgetu',
                'verbose_name_plural': 'Zliczenia odmów widgetu',
                'indexes': [models.Index(fields=['dzien', 'powod'], name='accounts_zl_dzien_b49f01_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'powod', 'dzien'), name='unikalne_zliczenie_odmow')],
            },
        ),
    ]
