# Generated by Django 5.2.17 on 2026-09-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_zliczenieodmow'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgloszonaCisza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_dnia', models.DateField(help_text='Pierwszy dzień bez rozmów')),
                ('zgloszone_dnia', models.DateField(auto_now_add=True)),
                ('dni_ciszy', models.PositiveIntegerField()),
                ('rozmow_przedtem', models.PositiveIntegerField(help_text='Ile rozmów firma miała w oknie odniesienia')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszone_ciszy', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Zgłoszona cisza widgetu',
                'verbose_name_plural': 'Zgłoszone ciszy widgetu',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'od_dnia'), name='unikalna_zgloszona_cisza')],
            },
        ),
    ]
