# Generated by Django 5.2.17 on 2026-09-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_zgloszonacisza'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZgloszonyRozmiar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog', models.PositiveIntegerField()),
                ('fragmentow', models.PositiveIntegerField(help_text='Ile bylo w chwili zgloszenia')),
                ('zgloszone_dnia', models.DateField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zgloszone_rozmiary', to='accounts.tenant')),
            ],
            options={
                'verbose_name': 'Zgłoszony rozmiar bazy wiedzy',
                'verbose_name_plural': 'Zgłoszone rozmiary baz wiedzy',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'prog'), name='unikalny_zgloszony_rozmiar')],
            },
        ),
    ]
