# Generated by Django 5.2.17 on 2026-09-10 17:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_zgloszonyrozmiar'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.CreateModel(
            name='MessageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cycle_id', models.UUIDField(null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('charged', 'charged'), ('released', 'released'), ('uncertain', 'uncertain')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'finished', 'expires_at'], name='reservation_active'), models.Index(fields=['subscription', 'cycle_id', 'state'], name='reservation_quota'), models.Index(fields=['tenant', 'is_test', 'created_at'], name='reservation_test_budget'), models.Index(fields=['tenant', 'created_at'], name='reservation_attempt_rate')],
            },
        ),
    ]
