# Generated by Django 5.2.17 on 2026-09-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_unique_account_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('token_digest', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('sent_at', models.DateTimeField(null=True)),
                ('window_start', models.DateTimeField()),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
