# Generated by Django 5.2.17 on 2026-09-11 11:39

import accounts.mfa_crypto
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def encrypt_seeds(apps, schema_editor):
    model = apps.get_model("accounts", "DrugiSkladnik")
    rows = model.objects.using(schema_editor.connection.alias)
    for row in rows.iterator(chunk_size=100):
        rows.filter(pk=row.pk).update(sekret=accounts.mfa_crypto.encrypt(row.sekret))


def decrypt_seeds(apps, schema_editor):
    model = apps.get_model("accounts", "DrugiSkladnik")
    rows = model.objects.using(schema_editor.connection.alias)
    for row in rows.iterator(chunk_size=100):
        rows.filter(pk=row.pk).update(sekret=accounts.mfa_crypto.decrypt(row.sekret))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_pending_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugiskladnik',
            name='sekret',
            field=models.TextField(),
        ),
        migrations.RunPython(encrypt_seeds, decrypt_seeds),
        migrations.AlterField(
            model_name='drugiskladnik',
            name='sekret',
            field=accounts.mfa_crypto.EncryptedMFAField(),
        ),
        migrations.CreateModel(
            name='MfaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(null=True)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
