# Generated by Django 5.2.17 on 2026-09-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0039_subscription_zmiany_stripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="skrot_skrzynki",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
    ]
