# Generated by Django 5.2.17 on 2026-09-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0041_proba_zakupu"),
    ]

    operations = [
        migrations.CreateModel(
            name="KontrolaStripe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("probowano_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("uzgodniono_at", models.DateTimeField(blank=True, null=True)),
                ("blad", models.CharField(blank=True, max_length=64)),
                ("alarm_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontrola_stripe",
                        to="accounts.tenant",
                    ),
                ),
            ],
        ),
    ]
