# Generated by Django 5.2.17 on 2026-09-30 12:17

import django.core.validators
from django.db import migrations, models


def sprawdz_zakres(apps, schema_editor):
    Tenant = apps.get_model("accounts", "Tenant")
    bledne = Tenant.objects.using(schema_editor.connection.alias).filter(
        data_retention_days__gt=3650
    )
    identyfikatory = list(bledne.order_by("pk").values_list("pk", flat=True)[:20])
    if identyfikatory:
        raise RuntimeError(
            f"Retencja poza zakresem, firmy: {identyfikatory}. "
            "Uruchom kontrola_retencji i uzgodnij okresy. Migracja nie zmienia danych."
        )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0042_kontrola_stripe"),
    ]

    operations = [
        migrations.RunPython(sprawdz_zakres, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tenant",
            name="data_retention_days",
            field=models.PositiveIntegerField(
                default=90,
                help_text="Po ilu dniach automatycznie usuwać rozmowy i logi. 0 = nie usuwaj.",
                validators=[django.core.validators.MaxValueValidator(3650)],
            ),
        ),
        migrations.AddConstraint(
            model_name="tenant",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_retention_days__lte", 3650)),
                name="tenant_retencja_obslugiwany_zakres",
            ),
        ),
    ]
