# Generated by Django 5.2.17 on 2026-09-30 13:14

import chatbot_project.pliki
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_usuwanie_retencja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='widget_avatar',
            field=models.FileField(blank=True, null=True, upload_to=chatbot_project.pliki.nazwa_brandingu),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='widget_logo',
            field=models.FileField(blank=True, null=True, upload_to=chatbot_project.pliki.nazwa_brandingu),
        ),
    ]
