# Generated by Django 5.2.17 on 2026-10-07 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_zaproszenie_token_wysylki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zliczenieodmow',
            name='powod',
            field=models.CharField(choices=[('brak_klucza', 'Żądanie bez klucza API'), ('zly_klucz', 'Nieznany klucz API'), ('brak_subskrypcji', 'Firma bez subskrypcji'), ('brak_aktywnej', 'Żadna subskrypcja nie jest aktywna'), ('subskrypcja_wygasla', 'Subskrypcja poza datami ważności'), ('limit_wiadomosci', 'Wyczerpany limit wiadomości'), ('serwer_zajety', 'Serwer zajęty: wszystkie miejsca na rozmowy w użyciu'), ('limit_rozmow_firmy', 'Firma ma naraz najwięcej rozmów, ile może')], max_length=32),
        ),
    ]
