# Generated by Django 5.1.7 on 2025-05-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tenant_gpt_prompt'),
        ('documents', '0005_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Strona WWW klienta', max_length=255)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_sources', to='accounts.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'url')},
            },
        ),
    ]
