# Generated by Django 5.1.7 on 2025-05-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_websitesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
