# Generated by Django 5.1.7 on 2026-08-10 10:38

from django.db import migrations, models


def uzupelnij_adresy_stron(apps, schema_editor):
    """
    Odzyskuje adresy stron zaimportowanych przed dodaniem tego pola.

    Crawler nazywał każdą podstronę jej własnym adresem, więc dla nich nazwa
    jest adresem i da się go przepisać. Strona główna zapisywana była pod nazwą
    opisową — tam adresu nie odtworzymy i zostaje pusty, czyli bez linku.
    Zawężamy do source="website": nazwa wgranego pliku nigdy nie jest adresem,
    a nawet gdyby ktoś tak nazwał dokument, linkowanie go byłoby błędem.
    """
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(
        source="website", source_url="", name__startswith="http"
    ).update(source_url=models.F("name"))


def cofnij(apps, schema_editor):
    """Pole znika razem z migracją — nie ma czego odtwarzać."""


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_url',
            field=models.URLField(blank=True, default='', help_text='Publiczny adres źródła. Pusty dla wgranych plików.'),
        ),
        migrations.RunPython(uzupelnij_adresy_stron, cofnij),
    ]
