# Generated by Django 5.1.7 on 2026-08-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesource',
            name='last_crawled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
