# Generated by Django 5.1.7 on 2026-08-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_websitesource_last_crawled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesource',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websitesource',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
