# Generated by Django 5.1.7 on 2026-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_slad_pobierania_zrodla'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uzywaj_w_wyszukiwaniu',
            field=models.BooleanField(default=True, verbose_name='Używaj w wyszukiwaniu'),
        ),
    ]
