# Generated by Django 5.1.7 on 2026-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_uzywaj_w_wyszukiwaniu'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='znakow_na_stronie',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
