# Generated by Django 5.2.17 on 2026-09-30 13:14

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_document_processing_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsunieciePliku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_id', models.BigIntegerField(blank=True, null=True)),
                ('magazyn', models.CharField(max_length=32)),
                ('cel', models.CharField(max_length=64)),
                ('nazwa', models.CharField(max_length=512)),
                ('stan', models.CharField(default='oczekuje', max_length=16)),
                ('proby', models.PositiveIntegerField(default=0)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('utworzono_at', models.DateTimeField(auto_now_add=True)),
                ('ponow_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dzierzawa_do', models.DateTimeField(blank=True, null=True)),
                ('zakonczono_at', models.DateTimeField(blank=True, null=True)),
                ('blad', models.CharField(blank=True, max_length=64)),
                ('alarm_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['stan', 'ponow_at'], name='plik_usun_due'), models.Index(fields=['stan', 'dzierzawa_do'], name='plik_usun_lease')],
            },
        ),
    ]
